---
baseurl: https://vapordev.netlify.app/
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: vapordev A.T. フィールド
favicon: img/favicon.png
disqusShortname: hugo-theme-stack
googleAnalytics:
DefaultContentLanguage: en
permalinks:
  post: "/p/:slug/"
  page: "/:slug/"
params:
  mainSections:
  - post
  featuredImageField: image
  rssFullContent: true
  favicon:
  footer:
    since: 2020
    customText:
  dateFormat:
    published: Jan 02, 2006
    lastUpdated: Jan 02, 2006 15:04 MST
  sidebar:
    emoji: "\U0001F365"
    subtitle: Sem tretas aqui, apenas conteúdo técnico.
    avatar:
      local: true
      src: img/perfil.jpeg
  article:
    math: false
    license:
      enabled: true
      default: Licensed under CC BY-NC-SA 4.0
  comments:
    enabled: false
    provider: disqus
    utterances:
      repo:
      issueTerm: pathname
      label:
    remark42:
      host:
      site:
      locale:
  widgets:
    enabled:
    - search
    - archives
    - tag-cloud
    archives:
      limit: 5
    tagCloud:
      limit: 10
  opengraph:
    twitter:
      site:
      card: summary_large_image
  defaultImage:
    opengraph:
      enabled: false
      local: false
      src:
  colorScheme:
    toggle: true
    default: auto
  imageProcessing:
    cover:
      enabled: true
    content:
      enabled: true
related:
  includeNewer: true
  threshold: 60
  toLower: false
  indices:
  - name: tags
    weight: 100
  - name: categories
    weight: 200
markup:
  highlight:
    noClasses: false
